### ISSUE TITLE
One-to-Many solution

### ISSUE THREAD

**Issue by edthepurple** [shawwwn/gole#4]
Hello..

first of all. thank you for this amazing project.
however, I have a question/problem?

what if we don't know the "client" public ip address? is there a way to use the tunnel for the sole purpose of port forwarding between point A and point B? so Point A has a static configuration and point B only needs to know point A's public ip and port?

**Comment by edthepurple** [comment]
Also i noticed that a port can only be used by one connection, the moment a second connection gets established; their packets get mixed up.

**Comment by shawwwn** [comment]
> what if we don't know the "client" public ip address?

If a computer can browse the internet, it must have a public IP address.

> is there a way to use the tunnel for the sole purpose of port forwarding between point A and point B

> Also i noticed that a port can only be used by one connection, the moment a second connection gets established; their packets get mixed up.

TCP+server/client takes care of the multiplexing of connections. However, a side must be either a server or a client since TCP is a connection-based protocol.

UDP protocol is connection-less, it doesn't have the concept of connection, packets are supposed to get mixed up.

**Comment by edthepurple** [comment]
I wanted to use it to make a domestic relay so my VPN clients can connect to my OpenVPN (UDP) server through that. something like UDP2RAW or SWGP-GO does.

**Comment by shawwwn** [comment]
Plain-old UDP tunnel doesn't work in your case and here is why: One hole can accommodate one tunnel. One UDP tunnel serves only one connection. One connection is defined by a four-tuple (src ip, src port, dest ip, dest port). If you have two clients trying to connect to one server, there will be two connections, therefore you will be needing two tunnels, so two holes on target NAT.

The solution is to use TCP/KCP tunnel.
TCP tunnel takes care of the multiplexing of connections (as I mentioned above).
KCP is a simulated TCP protocol on top of a UDP tunnel. It turns TCP traffic into UDP with various error correction mechanisms in order to achieve a high throughput under a lossy network environment.

The word 'connection' I using here is not a real connection(like a session) but rather a four-tuple matching scheme. Forgive my poor choice of words for I don't know how to express otherwise.

**Comment by edthepurple** [comment]
Thank you for your thorough explanation. I really appreciate it.
